### PR TITLE
update messages.po - Improvement in few sentences

### PR DESCRIPTION
**Pull request by luhad**
Improvement in a few sentences to make more sense in brazilian portuguese

[Review on Reviewable](https://reviewable.io/reviews/mozilla/commbadge/78)

### CODE REVIEW

**Comment by clouserw** [comment]
pinging @mathjazz to see if we should land

**Comment by mathjazz** [comment]
Adding @ouesten to review.

Please note that pt-BR uses Pontoon for Marketplace localization:
https://pontoon.mozilla.org/pt-br/

**Comment by ouesten** [comment]
Please, use Pontoon for Marketplace localization: https://pontoon.mozilla.org/pt-BR/marketplace-commbadge/

**Comment by luhad** [comment]
Ok, done !

**Comment by clouserw** [comment]
Hi, I've been away so haven't followed up on this.  I'm not sure what the above means -- I think it means these changes were committed through other channels and we should close this pull request?

**Comment by mathjazz** [comment]
Fine by me.

**Comment by clouserw** [comment]
Ok, thanks all

**Pull request closed without merging**
